dataset_str:
  "TartanGroundWAI(
    split='${dataset.tartanground.train.split}',
    resolution=${dataset.tartanground.train.dataset_resolution},
    principal_point_centered=${dataset.tartanground.train.principal_point_centered},
    aug_crop=${dataset.tartanground.train.aug_crop},
    transform='${dataset.tartanground.train.transform}',
    data_norm_type='${dataset.tartanground.train.data_norm_type}',
    ROOT='${dataset.tartanground.train.ROOT}',
    dataset_metadata_dir='${dataset.tartanground.train.dataset_metadata_dir}',
    overfit_num_sets=${dataset.tartanground.train.overfit_num_sets},
    variable_num_views=${dataset.tartanground.train.variable_num_views},
    num_views=${dataset.tartanground.train.num_views},
    max_num_retries=10,
    debug_by_vis=False,
    covisibility_thres=${dataset.tartanground.train.covisibility_thres})"
split: 'train'
dataset_resolution: ${dataset.resolution_train}
principal_point_centered: ${dataset.principal_point_centered}
aug_crop: 16
transform: 'colorjitter+grayscale+gaublur'
data_norm_type: ${model.data_norm_type}
ROOT: /drobotics-ailab/bohao.zhang/datasets/TartanGround-unzip
dataset_metadata_dir: ${mapanything_dataset_metadata_dir}
overfit_num_sets: null
variable_num_views: ${dataset.train.variable_num_views}
num_views: ${dataset.num_views}
covisibility_thres: 0.25
